import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';

const APP = process.cwd();
const ROOT = path.resolve(APP, '..');
const VERTICALS_DIR = path.join(ROOT, 'verticals');

// One entry per vertical this build ingests, each writing to its own .content/<vertical>/.
// fitness keeps its original, unchanged root-level paths (this script predates the
// multi-vertical migration and fitness's behavior must stay byte-for-byte identical).
// Every other vertical is auto-discovered as a subdirectory of verticals/ that has its
// own reports/ dir, no hardcoded vertical-slug list here, so this script can never drift
// out of sync with lib/verticals.ts (which it cannot import: this is a plain Node script
// that runs at predev/prebuild, before Next.js/TypeScript has compiled anything, so a
// second source of truth for "which verticals exist" would risk disagreeing with the
// registry; scanning the filesystem instead means there is only ever one).
function discoverSources() {
  const sources = [
    {
      vertical: 'fitness',
      reportsDir: path.join(ROOT, 'reports'),
      historyCsv: path.join(ROOT, 'data', 'history.csv'),
      branchReportsPrefix: 'reports',
    },
  ];
  if (fs.existsSync(VERTICALS_DIR)) {
    for (const name of fs.readdirSync(VERTICALS_DIR).sort()) {
      const reportsDir = path.join(VERTICALS_DIR, name, 'reports');
      if (fs.existsSync(reportsDir)) {
        sources.push({
          vertical: name,
          reportsDir,
          historyCsv: path.join(VERTICALS_DIR, name, 'data', 'history.csv'),
          branchReportsPrefix: `verticals/${name}/reports`,
        });
      }
    }
  }
  return sources;
}

// Self-healing: cloud routines commit each run on an ephemeral claude/* branch and
// are meant to merge the report to main. If a merge is missed, the report strands on
// its branch and this build (from main) would miss it. Best-effort sweep of the run
// branches for report .md files not on main, so every rebuild is comprehensive.
// Never throws: if git/network isn't available in the build sandbox, we log and skip.
function recoverBranchReports(existingNames, branchReportsPrefix) {
  const git = (cmd) => execSync(`git ${cmd}`, { cwd: ROOT, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], timeout: 90000 });
  const extras = [];
  try {
    git("fetch --depth=1 origin '+refs/heads/claude/*:refs/remotes/origin/claude/*'");
    const branches = git("for-each-ref --format='%(refname)' refs/remotes/origin/claude/")
      .split('\n').map((s) => s.trim()).filter(Boolean);
    const picked = new Map(); // basename -> { ts, ref, pathInRepo }
    for (const ref of branches) {
      let files;
      try {
        files = git(`ls-tree -r --name-only ${ref} -- ${branchReportsPrefix}`)
          .split('\n')
          .filter((f) => f.startsWith(branchReportsPrefix + '/') && f.endsWith('.md'));
      } catch {
        continue;
      }
      for (const f of files) {
        const base = f.slice(branchReportsPrefix.length + 1);
        if (existingNames.has(base)) continue;
        let ts = 0;
        try {
          ts = parseInt(git(`log -1 --format=%ct ${ref} -- ${f}`).trim(), 10) || 0;
        } catch {}
        const prev = picked.get(base);
        if (!prev || ts > prev.ts) picked.set(base, { ts, ref, pathInRepo: f });
      }
    }
    for (const [base, info] of picked) {
      try {
        extras.push({ name: base, text: git(`show ${info.ref}:${info.pathInRepo}`) });
      } catch {}
    }
    console.log(`ingest: [${branchReportsPrefix}] branch sweep saw ${branches.length} run branch(es), recovered ${extras.length} report(s) not on main`);
  } catch (e) {
    const msg = String(e && e.message ? e.message : e).split('\n')[0].slice(0, 100);
    console.log(`ingest: [${branchReportsPrefix}] branch sweep skipped (${msg})`);
  }
  return extras;
}

const YT = /(?:youtube\.com\/(?:watch\?v=|shorts\/|embed\/|live\/)|youtu\.be\/)([A-Za-z0-9_-]{11})/;
const NON_VIDEO_LINK = /youtube\.com\/(?:post\/|channel\/|c\/|user\/|@)/i;

// Competitor Radar data contract: repo-root competitor_data/<vertical>/ holds a
// registry.json plus per-competitor windows/*.json, generated by the research repo's
// exporter (never hand-authored). Copy it into .content/<vertical>/competitors/ so the
// dashboard reads it server-side like reports (never from public/). Additive and
// opportunistic: a vertical with no competitor_data just gets no radar, no error.
const SLUG_OK = /^[\w.-]+$/;
function ingestCompetitors(vertical, outDir) {
  const src = path.join(ROOT, 'competitor_data', vertical);
  const regSrc = path.join(src, 'registry.json');
  if (!fs.existsSync(regSrc)) return;
  let registry;
  try {
    registry = JSON.parse(fs.readFileSync(regSrc, 'utf8'));
  } catch (e) {
    console.log(`ingest: [${vertical}] competitor registry unreadable, skipping radar (${String(e.message).slice(0, 80)})`);
    return;
  }
  const dst = path.join(outDir, 'competitors');
  fs.mkdirSync(dst, { recursive: true });
  const kept = [];
  for (const comp of registry.competitors || []) {
    if (!comp || !SLUG_OK.test(comp.slug || '')) continue; // guard: slug becomes a path segment
    const winKept = [];
    for (const win of comp.windows || []) {
      if (!SLUG_OK.test(win)) continue;
      const winSrc = path.join(src, comp.slug, 'windows', `${win}.json`);
      if (!fs.existsSync(winSrc)) continue;
      const winDstDir = path.join(dst, comp.slug, 'windows');
      fs.mkdirSync(winDstDir, { recursive: true });
      fs.copyFileSync(winSrc, path.join(winDstDir, `${win}.json`));
      winKept.push(win);
    }
    // Optional month-wise insights (generated from all of this competitor's windows).
    const insSrc = path.join(src, comp.slug, 'insights.json');
    let hasInsights = false;
    if (fs.existsSync(insSrc)) {
      fs.mkdirSync(path.join(dst, comp.slug), { recursive: true });
      fs.copyFileSync(insSrc, path.join(dst, comp.slug, 'insights.json'));
      hasInsights = true;
    }
    kept.push({ ...comp, windows: winKept, hasInsights });
  }
  fs.writeFileSync(path.join(dst, 'registry.json'), JSON.stringify({ ...registry, competitors: kept }, null, 1));
  const totalWindows = kept.reduce((n, c) => n + c.windows.length, 0);
  console.log(`ingest: [${vertical}] competitor radar: ${kept.length} competitor(s), ${totalWindows} window(s)`);
}

function parseCSV(text) {
  const rows = [];
  let row = [], field = '', inQ = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQ) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else inQ = false;
      } else field += c;
    } else if (c === '"') inQ = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c !== '\r') field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

function loadHistory(historyCsvPath) {
  try {
    const rows = parseCSV(fs.readFileSync(historyCsvPath, 'utf8'));
    const header = rows[0];
    const di = header.indexOf('date');
    const vi = header.indexOf('video_or_post_id');
    if (di < 0 || vi < 0) return null;
    const byDate = new Map();
    const ids = new Set();
    for (const r of rows.slice(1)) {
      if (r.length <= Math.max(di, vi)) continue;
      byDate.set(r[di], (byDate.get(r[di]) || 0) + 1);
      if (r[vi]) ids.add(r[vi]);
    }
    return { byDate, ids, total: rows.length - 1 };
  } catch {
    return null;
  }
}

function segment(lines) {
  const segs = [];
  let cur = { heading: 'HEADER', lines: [] };
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/^[=-]{10,}\s*$/.test(line)) {
      const next = lines[i + 1] ?? '';
      const after = lines[i + 2] ?? '';
      if (next.trim() && /^[=-]{10,}\s*$/.test(after)) {
        segs.push(cur);
        cur = { heading: next.trim(), lines: [] };
        i += 2;
        continue;
      }
      continue;
    }
    cur.lines.push(line);
  }
  segs.push(cur);
  return segs;
}

function trimBlock(lines) {
  const out = lines.map((l) => l.replace(/\s+$/, ''));
  while (out.length && !out[0].trim()) out.shift();
  while (out.length && !out[out.length - 1].trim()) out.pop();
  return out;
}

function parseDailyPicks(lines) {
  const picks = [];
  const extras = [];
  let cur = null;
  let extraCur = null;
  let mode = 'picks';
  const flush = () => { if (cur) { picks.push(cur); cur = null; } };
  for (const raw of lines) {
    const t = raw.trim();
    const start = t.match(/^(\d+)\.\s+\[([A-Z ]+)\]\s+(.*)$/);
    const extraHead = t.match(/^([A-Z][A-Z0-9 '&/()-]*):(\s*\S.*)?$/);
    const isKnownField = /^(Title|Link|Strategist take):/.test(t) || /^VPH\b/.test(t);
    if (mode === 'picks' && start) {
      flush();
      cur = { rank: +start[1], format: start[2].trim(), hook: start[3].trim(), title: '', channel: '', stats: '', link: '', videoId: null, take: '' };
      continue;
    }
    if (extraHead && !isKnownField && !start) {
      flush();
      mode = 'extras';
      extraCur = { label: extraHead[1].trim(), lines: [] };
      extras.push(extraCur);
      if (extraHead[2] && extraHead[2].trim()) extraCur.lines.push(extraHead[2].trim());
      continue;
    }
    if (mode === 'extras') {
      if (t && extraCur) extraCur.lines.push(t);
      continue;
    }
    if (!cur) continue;
    if (t.startsWith('Title:')) cur.title = t.slice(6).trim();
    else if (t.startsWith('Link:')) {
      cur.link = t.slice(5).trim();
      cur.videoId = (cur.link.match(YT) || [])[1] || null;
    } else if (t.startsWith('Strategist take:')) cur.take = t.slice(16).trim();
    else if (/^VPH\b/.test(t)) cur.stats = t;
    else if (t && cur.title && !cur.channel && !cur.stats) cur.channel = t;
    else if (t && cur.take) cur.take += ' ' + t;
  }
  flush();
  return { picks, extras };
}

function parseWeeklyPage1(lines) {
  const groups = [];
  let g = null;
  let winner = null;
  const flushW = () => { if (winner && g) { g.winners.push(winner); winner = null; } };
  for (const raw of lines) {
    const t = raw.trim();
    const head = t.match(/^([A-Z][A-Z0-9 '&/-]*)(\s*\([^)]*\))?:\s*$/);
    if (head) {
      flushW();
      g = { label: (head[1] + (head[2] || '')).trim(), winners: [], lines: [] };
      groups.push(g);
      continue;
    }
    if (!g) continue;
    const start = t.match(/^(\d+)\.\s+\[([A-Z ]+)\]\s+(.*)$/);
    if (start) {
      flushW();
      winner = { rank: +start[1], format: start[2].trim(), title: start[3].trim(), channel: '', take: '', link: '', videoId: null };
      continue;
    }
    if (winner) {
      if (t.startsWith('Strategist take:')) winner.take = t.slice(16).trim();
      else if (t.startsWith('Link:')) {
        winner.link = t.slice(5).trim();
        winner.videoId = (winner.link.match(YT) || [])[1] || null;
      } else if (!winner.channel && t) winner.channel = t;
      else if (winner.take && t) winner.take += ' ' + t;
      continue;
    }
    if (t) g.lines.push(t);
  }
  flushW();
  return groups;
}

function parseSectionEntries(lines) {
  const entries = [];
  let cur = null;
  let lastKey = null;
  for (const raw of lines) {
    const t = raw.trim();
    const head = t.match(/^\[(\d+)\]\s+([A-Z ]+)\s*\|\s*(.*)$/);
    if (head) {
      if (cur) entries.push(cur);
      cur = { rank: +head[1], format: head[2].trim(), title: head[3].trim(), fields: {}, videoId: null };
      lastKey = null;
      continue;
    }
    if (!cur) continue;
    const kv = t.match(/^(Channel|Posted|Views|Engagement|Flags|Link|Thumbnail|Why|Strategist take|Audience read):\s*(.*)$/);
    if (kv) {
      lastKey = kv[1];
      cur.fields[lastKey] = kv[2];
      if (lastKey === 'Link') cur.videoId = (kv[2].match(YT) || [])[1] || null;
    } else if (t && lastKey) {
      cur.fields[lastKey] += ' ' + t;
    }
  }
  if (cur) entries.push(cur);
  return entries;
}

function parseReport(file, text, history) {
  const name = path.basename(file, '.md');
  const m = name.match(/^(\d{4}-\d{2}(-\d{2})?)_(daily|weekly|retro)$/);
  if (!m) return null;
  const kind = m[3] === 'retro' ? 'monthly' : m[3];
  const lines = text.split('\n');
  const headerTitle = (lines[0] || '').trim();
  const generated = (lines.find((l) => l.startsWith('Generated')) || '').trim();
  const sources = (lines.find((l) => l.startsWith('Sources:')) || '').trim();
  let date = m[1];
  if (kind === 'monthly') {
    date = (generated.match(/(\d{4}-\d{2}-\d{2})/) || [])[1] || m[1] + '-01';
  }

  const segs = segment(lines).map((s) => ({ heading: s.heading, lines: trimBlock(s.lines) }));
  const checks = [];
  const check = (label, ok, note, level = 'warn') => checks.push({ label, ok: !!ok, note: ok ? '' : note, level });

  let picks = [];
  let extras = [];
  let weeklyGroups = [];
  let preface = [];
  const sections = [];

  for (const seg of segs) {
    const h = seg.heading.toUpperCase();
    if (h === 'HEADER') continue;
    if (h.startsWith('PREFACE')) { preface = seg.lines; continue; }
    if (h.startsWith('PAGE 1')) {
      if (kind === 'daily') {
        const r = parseDailyPicks(seg.lines);
        picks = r.picks;
        extras = r.extras;
      } else if (kind === 'weekly') {
        weeklyGroups = parseWeeklyPage1(seg.lines);
      } else {
        sections.push({ name: seg.heading, entries: [], lines: seg.lines });
      }
      continue;
    }
    if (h.startsWith('FULL SECTIONS')) continue;
    const entries = parseSectionEntries(seg.lines);
    sections.push({ name: seg.heading, entries, lines: seg.lines });
  }

  check('report parsed', segs.length > 1, 'no recognizable sections found', 'hold');
  check('date recognized', /^\d{4}-\d{2}-\d{2}$/.test(date), `could not resolve a calendar date (${date})`, 'hold');

  if (kind === 'daily') {
    check('top picks present', picks.length > 0, 'PAGE 1 yielded zero picks');
    const funnel = preface.join(' ').match(/->\s*(\d+)\s+ranked picks/);
    if (funnel) check('pick count matches funnel', picks.length === +funnel[1], `report claims ${funnel[1]} picks, parsed ${picks.length}`);
    const noId = picks.filter((p) => p.link && !p.videoId && !NON_VIDEO_LINK.test(p.link));
    check('video ids extracted', noId.length === 0, `${noId.length} pick(s) with unparseable video link`);
    check('header date matches filename', headerTitle.includes(m[1]), `header says "${headerTitle}"`);
    if (history) {
      check('history has rows for this date', (history.byDate.get(date) || 0) > 0, `history.csv has no rows dated ${date}`);
      const missing = picks.filter((p) => p.videoId && !history.ids.has(p.videoId)).map((p) => p.videoId);
      check('picks exist in history ledger', missing.length === 0, `not in history.csv: ${missing.slice(0, 3).join(', ')}${missing.length > 3 ? '…' : ''}`);
    } else {
      check('history.csv loaded', false, 'could not load data/history.csv for cross-verification');
    }
  }
  if (kind === 'weekly') {
    const winners = weeklyGroups.flatMap((g) => g.winners);
    check('weekly winners present', winners.length > 0, 'no durable winners parsed');
    check('header date matches filename', headerTitle.includes(m[1]), `header says "${headerTitle}"`);
  }
  if (kind === 'monthly') {
    check('retro sections present', sections.length > 0, 'no sections parsed');
  }

  const held = checks.some((c) => !c.ok && c.level === 'hold');
  const warned = checks.some((c) => !c.ok && c.level === 'warn');
  const status = held ? 'held' : warned ? 'warned' : 'verified';

  const allVideoIds = [
    ...picks.map((p) => p.videoId),
    ...weeklyGroups.flatMap((g) => g.winners.map((w) => w.videoId)),
    ...sections.flatMap((s) => s.entries.map((e) => e.videoId)),
  ].filter(Boolean);

  return {
    slug: name,
    kind,
    date,
    month: m[1].slice(0, 7),
    headerTitle,
    generated,
    sources,
    preface,
    picks,
    extras,
    weeklyGroups,
    sections,
    raw: text,
    videoCount: allVideoIds.length,
    verification: { status, checks },
  };
}

function ingestSource(source) {
  const { vertical, reportsDir, historyCsv, branchReportsPrefix } = source;
  const history = loadHistory(historyCsv);
  const onDisk = fs.readdirSync(reportsDir).filter((f) => f.endsWith('.md')).sort();
  const sources = onDisk.map((f) => ({ name: f, text: fs.readFileSync(path.join(reportsDir, f), 'utf8'), recovered: false }));
  // self-healing: pull any report stranded on a run branch and not present on main
  for (const extra of recoverBranchReports(new Set(onDisk), branchReportsPrefix)) {
    sources.push({ name: extra.name, text: extra.text, recovered: true });
  }
  const reports = [];
  const issues = [];

  for (const src of sources) {
    const r = parseReport(src.name, src.text, history);
    if (!r) {
      issues.push({ slug: src.name, level: 'held', msg: 'unrecognized filename pattern; not published' });
      continue;
    }
    r.recovered = src.recovered;
    reports.push(r);
    for (const c of r.verification.checks) {
      if (!c.ok) issues.push({ slug: r.slug, level: c.level === 'hold' ? 'held' : 'warning', msg: `${c.label}: ${c.note}` });
    }
  }

  const published = reports.filter((r) => r.verification.status !== 'held');
  const kindOrder = { daily: 0, weekly: 1, monthly: 2 };
  published.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : kindOrder[a.kind] - kindOrder[b.kind]));

  const byDate = {};
  for (const r of published) {
    (byDate[r.date] = byDate[r.date] || []).push({ slug: r.slug, kind: r.kind, status: r.verification.status });
  }

  const latestDaily = [...published].reverse().find((r) => r.kind === 'daily');
  const latest = latestDaily || published[published.length - 1] || null;

  const manifest = {
    generatedAt: new Date().toISOString(),
    historyRows: history ? history.total : null,
    latestSlug: latest ? latest.slug : null,
    latestDate: latest ? latest.date : null,
    byDate,
    reports: published.map((r) => ({
      slug: r.slug,
      kind: r.kind,
      date: r.date,
      month: r.month,
      status: r.verification.status,
      pickCount: r.kind === 'daily' ? r.picks.length : r.kind === 'weekly' ? r.weeklyGroups.reduce((n, g) => n + g.winners.length, 0) : 0,
      videoCount: r.videoCount,
    })),
    heldSlugs: reports.filter((r) => r.verification.status === 'held').map((r) => r.slug),
    issues,
  };

  const out = path.join(APP, '.content', vertical);
  fs.rmSync(out, { recursive: true, force: true });
  fs.mkdirSync(path.join(out, 'reports'), { recursive: true });
  fs.writeFileSync(path.join(out, 'manifest.json'), JSON.stringify(manifest, null, 1));
  for (const r of reports) {
    fs.writeFileSync(path.join(out, 'reports', r.slug + '.json'), JSON.stringify(r));
  }
  // Competitor Radar is a strictly additive, secondary surface. It must never be able
  // to fail the main report build (the primary deliverable), so any error here is caught
  // and downgraded to a skipped radar; the reports above are already written and stand.
  try {
    ingestCompetitors(vertical, out);
  } catch (e) {
    console.log(`ingest: [${vertical}] competitor radar skipped (${String(e && e.message ? e.message : e).slice(0, 100)})`);
  }

  const counts = published.reduce((acc, r) => ((acc[r.verification.status] = (acc[r.verification.status] || 0) + 1), acc), {});
  console.log(`ingest: [${vertical}] ${published.length} published (${JSON.stringify(counts)}), ${manifest.heldSlugs.length} held, ${issues.length} issue note(s), history rows: ${manifest.historyRows}`);
}

function main() {
  const sources = discoverSources();
  // fitness must hard-fail the build if its reports dir is missing, unchanged from the
  // original single-vertical behavior. Every other vertical is opportunistic: absence
  // just means discoverSources() never added it, so it is silently skipped below (the
  // dashboard's own pending/empty-state handling covers a vertical with no content yet).
  const fitness = sources.find((s) => s.vertical === 'fitness');
  if (!fitness || !fs.existsSync(fitness.reportsDir)) {
    console.error(`ingest: reports directory not found at ${fitness ? fitness.reportsDir : path.join(ROOT, 'reports')}`);
    process.exit(1);
  }
  for (const source of sources) {
    ingestSource(source);
  }
}

main();
